name = "r2-browser-backend"
main = "src/index.ts"
compatibility_date = "2023-11-21"

[vars]
ACCESS_KEY_ID = "d9ec0671312fc3e7437dc59bd7124b1e"

[[r2_buckets]]
binding = "DOWNLOAD"
bucket_name = "download"
preview_bucket_name = "download-preview"
